require 'octonaut/printers/base'
require 'octonaut/printers/authorizations'
require 'octonaut/printers/collaborators'
require 'octonaut/printers/repositories'
require 'octonaut/printers/users'
require 'octonaut/printers/organizations'
